name = "MarkNext"
grammar = "marknext"
path_suffixes = ["mnext", "mn"]
line_comments = ["% ", "# "]
tab_size = 2
hard_tabs = false

[brackets]
open = ["[", "(", "{", "```", "`", "*", "/", "[^", "$$", "$"]
close = ["]", ")", "}", "```", "`", "*", "/", "]", "$$", "$"]

autoclose_before = "`'

brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "```", end = "```", close = true, newline = true },
    { start = "`", end = "`", close = true, newline = false },
    { start = "*", end = "*", close = true, newline = false },
    { start = "/", end = "/", close = true, newline = false },
    { start = "[^", end = "]", close = true, newline = false },
    { start = "$$", end = "$$", close = true, newline = true },
    { start = "$", end = "$", close = true, newline = false },
]
