name = "MarkNext"
version = "1.0.0"
authors = ["Sebastian Korotkiewicz"]
description = "Syntax highlighting for MarkNext - a minimal, unambiguous, and secure Markdown successor"
repository = "https://github.com/skorotkiewicz/marknext"

[language_servers]
marknext = { name = "MarkNext Language Server", language = "MarkNext" }

[[languages]]
name = "MarkNext"
grammar = "marknext"
path_suffixes = ["mnext", "mn"]
line_comments = ["% "]
autoclose_before = "`'
brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "```", end = "```", close = true, newline = true },
    { start = "`", end = "`", close = true, newline = false },
    { start = "*", end = "*", close = true, newline = false },
    { start = "/", end = "/", close = true, newline = false },
]
